<?php

namespace Neoan3\Component\svg;

use Neoan3\Core\Unicore;

/**
 * Class svgController
 * @package Neoan3\Component\svg
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class svgController extends Unicore{
    /**
     * Route: svg
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'svg')
            ->output();
    }

}