<?php

namespace Neoan3\Component\The;

use Neoan3\Core\Unicore;

/**
 * Class TheController
 * @package Neoan3\Component\The
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class TheController extends Unicore{
    /**
     * Route: The
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'the')
            ->output();
    }

}