<?php

namespace Neoan3\Component\Installation;

use Neoan3\Core\Unicore;

/**
 * Class InstallationController
 * @package Neoan3\Component\Installation
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class InstallationController extends Unicore{
    /**
     * Route: Installation
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'installation')
            ->output();
    }

}