<?php

namespace Neoan3\Component\Colors;

use Neoan3\Core\Unicore;

/**
 * Class ColorsController
 * @package Neoan3\Component\Colors
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ColorsController extends Unicore{
    /**
     * Route: Colors
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'colors')
            ->output();
    }

}