<?php

namespace Neoan3\Component\Layout;

use Neoan3\Core\Unicore;

/**
 * Class LayoutController
 * @package Neoan3\Component\Layout
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class LayoutController extends Unicore{
    /**
     * Route: Layout
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'layout')
            ->output();
    }

}