<?php

namespace Neoan3\Component\Documentation;

use Neoan3\Core\Unicore;

/**
 * Class DocumentationController
 * @package Neoan3\Component\Documentation
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */
class DocumentationController extends Unicore
{
    public static array $files,$links;

    /**
     * Route: Documentation
     */
    function init(): void
    {
        self::$links = self::linkCreator();
        $this
            ->uni('Ornate')
            ->hook('main', 'basic', ['links' => self::$links])
            ->output();
    }

    public static function linkCreator(): array
    {
        $results = [];
        self::$files = scandir(path . '/component');
        foreach (self::$files as $key => $file) {
            if ($file === '.' || $file === '..' || $file === 'Search' || $file === 'Footer'
                || $file === 'Navbar' || $file === 'NotFound' || $file === 'Documentation' ||
                $file === 'Home' || $file === 'Installation') {
                unset(self::$files[$key]);
            } else {
                $results[$key] = lcfirst($file);
            }
        }
        return $results;
    }
}