<?php

namespace Neoan3\Component\Search;

use Neoan3\Frame\Ornate;

/**
 * Class SearchController
 * @package Neoan3\Component\Search
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */
class SearchController extends Ornate
{
    public static array $results, $files;
    /**
     * GET: api.v1/search
     * GET: api.v1/search/{id}
     * GET: api.v1/search?{query-string}
     * @param string|null $body
     * @return string|null
     */
    function getSearch(?string $body = null): ?string
    {
        $results = [];
        $files = scandir(path . '/component');

        foreach ($files as $key => $file) {
            if ($file === '.' || $file === '..' || $file === 'Search' || $file === 'Footer'
                || $file === 'Navbar' || $file === 'NotFound') {
                unset($files[$key]);
            }
            $finalKey = array_search($body, $files);
            if ($finalKey) {
                $results = $files[$finalKey];
            } else {
                $results = 'failed';
            }
        }
        return $results;
    }

}
