<?php

namespace Neoan3\Component\Compositions;

use Neoan3\Core\Unicore;

/**
 * Class CompositionsController
 * @package Neoan3\Component\Compositions
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class CompositionsController extends Unicore{
    /**
     * Route: Compositions
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'compositions')
            ->output();
    }

}