<?php

namespace Neoan3\Component\PreBuilt;

use Neoan3\Core\Unicore;

/**
 * Class PreBuiltController
 * @package Neoan3\Component\PreBuilt
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class PreBuiltController extends Unicore{
    /**
     * Route: PreBuilt
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'preBuilt')
            ->output();
    }

}