<?php

namespace Neoan3\Component\Borders;

use Neoan3\Core\Unicore;

/**
 * Class BordersController
 * @package Neoan3\Component\Borders
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class BordersController extends Unicore{
    /**
     * Route: Borders
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'borders')
            ->output();
    }

}