<?php

namespace Neoan3\Component\Basic;

use Neoan3\Component\Documentation\DocumentationController;
use Neoan3\Core\Unicore;

/**
 * Class BasicController
 * @package Neoan3\Component\Basic
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class BasicController extends Unicore
{
    /**
     * Route: Basic
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main',
                   'basic',
                         ['links'=> DocumentationController::linkCreator()])
            ->output();
    }

}