<?php

namespace Neoan3\Component\Effects;

use Neoan3\Component\Documentation\DocumentationController;
use Neoan3\Core\Unicore;

/**
 * Class EffectsController
 * @package Neoan3\Component\Effects
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class EffectsController extends Unicore{
    /**
     * Route: Effects
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main',
                   'effects',
                   ['links' => DocumentationController::linkCreator()])
            ->output();
    }

}