<?php

namespace Neoan3\Component\Placement;

use Neoan3\Core\Unicore;

/**
 * Class PlacementController
 * @package Neoan3\Component\Placement
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class PlacementController extends Unicore{
    /**
     * Route: Placement
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'placement')
            ->output();
    }

}