<?php

namespace Neoan3\Component\Responsiveness;

use Neoan3\Core\Unicore;

/**
 * Class ResponsivenessController
 * @package Neoan3\Component\Responsiveness
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ResponsivenessController extends Unicore{
    /**
     * Route: Responsiveness
     */
    function init(): void
    {
        $this
            ->uni('Ornate')
            ->hook('main', 'responsiveness')
            ->output();
    }

}